### ISSUE TITLE
Permission Denied 

### ISSUE THREAD

**Issue by nietzschetmh** [JmPotato/Pomash#5]
Hi, I am following your instructions and using Amazon EC2.

When I go to this step **pip install -r requirements.txt**, i got error permission denied. I tried to run

sudo pip install -r requirements.txt but got an error sudo: pip: command not found. 

Any idea how to solve this?

Thanks.

**Comment by JmPotato** [comment]
My apology first. I'm sorry to reply you so late.

It seems that you didn't install the `pip`

Try to run:

```
sudo apt-get install pip
```

Then you can make it run perfectly!
